// CairnX suite — fully OFFLINE (no live chain, no live CairnX service):
//   • byte-exact record fixtures: the transfer uri + sha256 are pinned against ground truth
//     generated by @inversealtruism/cairnx-core (the resolver's own builder), so the CLI's
//     hand-rolled canonical JSON can never drift from what the resolver replays
//   • human→base amount conversion edges (pure string/BigInt math — no floats, no truncation)
//   • API base fallback order (env → local → public; network failure falls through, an HTTP
//     404 from a reachable base does NOT)
//   • the token-send --dry-run path + balance/decimals guards, via the real built CLI
//     against an in-process mock CairnX API (async spawn — same pattern as security.mjs)
import { spawn } from "node:child_process";
import http from "node:http";

const CLI = new URL("../dist/cli.js", import.meta.url).pathname;
let pass = 0, fail = 0;
const check = (n, c) => { c ? pass++ : fail++; console.log((c ? "  ✅ " : "  ❌ ") + n); };
const strip = (s) => s.replace(/\x1b\[[0-9;]*m/g, "");
function run(args, env = {}) {
  return new Promise((resolve) => {
    const ch = spawn("node", [CLI, ...args], { stdio: ["ignore", "pipe", "pipe"], env: { ...process.env, NO_COLOR: "1", CAIRN_CSD: "/nonexistent/csd", CAIRN_ADDR: "", CAIRN_CLI_CONFIG: "/nonexistent/cfg.json", CAIRN_API: "http://127.0.0.1:9", ...env } });
    let out = "";
    ch.stdout.on("data", (d) => (out += d));
    ch.stderr.on("data", (d) => (out += d));
    ch.on("close", (code) => resolve({ out: strip(out), raw: out, code }));
    setTimeout(() => ch.kill("SIGKILL"), 18000);
  });
}

const { buildTransferRecord, humanToBase, baseToHuman, defaultBases, cairnxGet, MAX_AMOUNT } =
  await import("../dist/lib/cairnx.js");

console.log("cairn-cli CAIRNX suite (offline)\n");

// ── byte-exact record fixtures (ground truth: @inversealtruism/cairnx-core transfer()) ──
console.log("— canonical transfer records: byte-exact vs cairnx-core ground truth —");
const FIXTURES = [
  { in: { ticker: "CAIRN", to: "0x44d92872a5b65d37d60ed532f41efe7c5aed59ec", amount: 150000000n },
    uri: '{"amount":"150000000","t":"transfer","ticker":"CAIRN","to":"0x44d92872a5b65d37d60ed532f41efe7c5aed59ec","v":1}',
    ph: "0xe8ccd4a195330de0808b94875623b2142bca0b071541108c0229e0881429dbec" },
  { in: { ticker: "XE5XNS", to: "0x0cc117e41053fabfff4c6daf92215ec4319f784f", amount: 1n },
    uri: '{"amount":"1","t":"transfer","ticker":"XE5XNS","to":"0x0cc117e41053fabfff4c6daf92215ec4319f784f","v":1}',
    ph: "0x24b19158c13e0df13a72cc1831c8b1810fc5ca843f81dfdf1655603b4a1cb2f0" },
  { in: { ticker: "ABC", to: "0x" + "ff".repeat(20), amount: (1n << 96n) - 1n }, // MAX_AMOUNT boundary
    uri: '{"amount":"79228162514264337593543950335","t":"transfer","ticker":"ABC","to":"0xffffffffffffffffffffffffffffffffffffffff","v":1}',
    ph: "0x59eff47e3b18cb09720dcb7c812a228f12f573cc7c7c28dcfb1a392cd00849ff" },
];
for (const f of FIXTURES) {
  const b = buildTransferRecord(f.in);
  check(`uri bytes exact   (${f.in.ticker} ${f.in.amount})`, b.uri === f.uri);
  check(`payloadHash exact (${f.ph.slice(0, 14)}…)`, b.payloadHash === f.ph);
}
check("recipient is lowercased into the record", buildTransferRecord({ ticker: "ABC", to: "0x" + "FF".repeat(20), amount: 1n }).uri.includes("0x" + "ff".repeat(20)));
const throws = (fn) => { try { fn(); return false; } catch { return true; } };
check("rejects amount 0", throws(() => buildTransferRecord({ ticker: "ABC", to: "0x" + "ff".repeat(20), amount: 0n })));
check("rejects amount > 2^96-1", throws(() => buildTransferRecord({ ticker: "ABC", to: "0x" + "ff".repeat(20), amount: 1n << 96n })));
check("rejects a lowercase ticker", throws(() => buildTransferRecord({ ticker: "abc", to: "0x" + "ff".repeat(20), amount: 1n })));
check("rejects a 2-char ticker", throws(() => buildTransferRecord({ ticker: "AB", to: "0x" + "ff".repeat(20), amount: 1n })));
check("rejects a 13-char ticker", throws(() => buildTransferRecord({ ticker: "A".repeat(13), to: "0x" + "ff".repeat(20), amount: 1n })));
check("rejects a malformed recipient", throws(() => buildTransferRecord({ ticker: "ABC", to: "0xshort", amount: 1n })));

// ── human → base conversion (string math; fail-don't-truncate) ──
console.log("\n— amount conversion: humanToBase / baseToHuman —");
check('"1" @ 8 decimals → 100000000', humanToBase("1", 8) === 100000000n);
check('"1.5" @ 8 → 150000000', humanToBase("1.5", 8) === 150000000n);
check('"0.00000001" @ 8 → 1 (smallest unit)', humanToBase("0.00000001", 8) === 1n);
check('"21000000" @ 8 → full CAIRN supply', humanToBase("21000000", 8) === 2100000000000000n);
check('"7" @ 0 decimals → 7', humanToBase("7", 0) === 7n);
check('".5" @ 1 → 5 (bare leading dot ok)', humanToBase(".5", 1) === 5n);
check('"1.50" @ 1 → 15 (trailing zeros are exact, not an error)', humanToBase("1.50", 1) === 15n);
check('"1.000" @ 0 → 1 (all-zero frac is exact)', humanToBase("1.000", 0) === 1n);
check('"0" @ 8 → 0 (the command layer rejects zero sends)', humanToBase("0", 8) === 0n);
check('"1.5" @ 0 decimals FAILS (never truncates to 1)', throws(() => humanToBase("1.5", 0)));
check('"1.05" @ 1 FAILS (0.05 not representable)', throws(() => humanToBase("1.05", 1)));
check('"0.000000001" @ 8 FAILS (sub-unit)', throws(() => humanToBase("0.000000001", 8)));
check("max amount accepted exactly (2^96-1 @ 0)", humanToBase(MAX_AMOUNT.toString(), 0) === MAX_AMOUNT);
check("overflow guard: 2^96 @ 0 FAILS", throws(() => humanToBase((1n << 96n).toString(), 0)));
check("overflow guard: huge digit string FAILS fast", throws(() => humanToBase("9".repeat(41), 0)));
for (const bad of ["", " ", "-1", "1e5", "0x10", "1,000", "abc", "1.2.3", ".", "+1", "NaN", "Infinity"])
  check(`rejects ${JSON.stringify(bad)}`, throws(() => humanToBase(bad, 8)));
check('baseToHuman(150000000, 8) → "1.5"', baseToHuman(150000000n, 8) === "1.5");
check('baseToHuman(1, 8) → "0.00000001"', baseToHuman(1n, 8) === "0.00000001");
check('baseToHuman("2100000000000000", 8) → "21000000" (string input)', baseToHuman("2100000000000000", 8) === "21000000");
check('baseToHuman(5, 0) → "5"', baseToHuman(5n, 0) === "5");
check('baseToHuman(0, 8) → "0"', baseToHuman(0n, 8) === "0");
check("round-trips exactly", ["1", "1.5", "0.00000001", "123456.789", "0.1"].every((h) => baseToHuman(humanToBase(h, 8), 8) === h));

// ── API base resolution + fallback order ──
console.log("\n— API base resolution order —");
const savedEnv = process.env.CAIRNX_API;
process.env.CAIRNX_API = "http://example.test/cairnx/";
check("env CAIRNX_API wins (and is used exclusively, trailing / stripped)", JSON.stringify(defaultBases()) === JSON.stringify(["http://example.test/cairnx"]));
delete process.env.CAIRNX_API;
const dflt = defaultBases();
check("without env: local service first, public gateway second", dflt[0] === "http://127.0.0.1:8794/cairnx" && dflt[1] === "https://cairn-substrate.com/trade/api/cairnx" && dflt.length === 2);
if (savedEnv !== undefined) process.env.CAIRNX_API = savedEnv;

// two tiny mock bases: A (down or hostile) and B (alive) — fallback is observable
const mkServer = (handler) => new Promise((res) => { const s = http.createServer(handler); s.listen(0, "127.0.0.1", () => res(s)); });
const baseOf = (s) => `http://127.0.0.1:${s.address().port}/cairnx`;
const json = (res, code, obj) => { res.statusCode = code; res.setHeader("content-type", "application/json"); res.end(JSON.stringify(obj)); };
const sA = await mkServer((req, res) => {
  if (req.url === "/cairnx/tokens") return json(res, 200, [{ ticker: "AAA", from: "A" }]);
  return json(res, 404, { ok: false, error: "unregistered name" });
});
const sB = await mkServer((req, res) => json(res, 200, [{ ticker: "BBB", from: "B" }]));
const A = baseOf(sA), B = baseOf(sB), DEAD = "http://127.0.0.1:9/cairnx";
check("dead first base falls through to the next", (await cairnxGet("/tokens", [DEAD, B]))[0].from === "B");
check("first ALIVE base wins (no eager fallback)", (await cairnxGet("/tokens", [A, B]))[0].from === "A");
check("all bases dead → friendly error naming the bases", await cairnxGet("/tokens", [DEAD]).then(() => false, (e) => /cannot reach/i.test(e.message) && e.message.includes(DEAD)));
const e404 = await cairnxGet("/name/zzz", [A, B]).then(() => null, (e) => e);
check("HTTP 404 from a reachable base is authoritative (never falls through to B)", e404 !== null && e404.status === 404 && /unregistered/.test(e404.message));

// ── the built CLI vs a mock CairnX API (read commands + the token-send dry-run path) ──
console.log("\n— CLI vs mock CairnX API —");
const ME = "0x" + "aa".repeat(20), YOU = "0x" + "bb".repeat(20);
const EVIL = "\x1b[2J\x1b[1;1Hpwned\x1b]0;hijack\x07FAKE"; // hostile ANSI/OSC in server fields
const TOKENS = [
  { ticker: "CAIRN", deployId: "0x" + "11".repeat(32), deployer: YOU, name: "Cairn" + EVIL, decimals: 8, supply: "2100000000000000", minted: "2100000000000000", mint: "issuer", height: 30279 },
  { ticker: "DEC0", deployId: "0x" + "22".repeat(32), deployer: YOU, name: "ZeroDec", decimals: 0, supply: "1000", minted: "1000", mint: "open", mintLimit: "10", height: 100 },
];
const mock = await mkServer((req, res) => {
  const u = new URL(req.url, "http://x");
  if (u.pathname === "/cairnx/tokens") return json(res, 200, TOKENS);
  if (u.pathname === "/cairnx/token/CAIRN") return json(res, 200, { ...TOKENS[0], holders: Object.fromEntries(Array.from({ length: 12 }, (_, i) => [("0x" + String(i).padStart(2, "0").repeat(20)).slice(0, 42), { available: String((12 - i) * 100000000), locked: "0" }])) });
  if (u.pathname === "/cairnx/token/DEC0") return json(res, 200, { ...TOKENS[1], holders: { [ME]: { available: "100", locked: "0" } } });
  if (u.pathname.startsWith("/cairnx/token/")) return json(res, 404, { ok: false, error: "unknown token" });
  if (u.pathname === `/cairnx/address/${ME}`) return json(res, 200, { address: ME, balances: { CAIRN: { available: "500000000", locked: "100000000" }, DEC0: { available: "100", locked: "0" } }, names: ["inverse", "stone-age"] });
  if (u.pathname.startsWith("/cairnx/address/")) return json(res, 200, { address: u.pathname.split("/").pop(), balances: {}, names: [] });
  if (u.pathname === "/cairnx/name/inverse") return json(res, 200, { name: "inverse", owner: ME, claimId: "0x" + "33".repeat(32), height: 30228, effectiveHeight: 30228, locked: false, offer: null });
  if (u.pathname === "/cairnx/name/leased") return json(res, 200, { name: "leased", owner: ME, claimId: "0x" + "44".repeat(32), height: 100, effectiveHeight: 100, locked: false, paidThroughEpoch: 2000, offer: { id: "0x" + "55".repeat(32), seller: ME, want: { value: "30000000" } } });
  return json(res, 404, { ok: false, error: "unregistered name" });
});
const MOCK = baseOf(mock);
const env = { CAIRNX_API: MOCK };

const tk = await run(["tokens", ME], env);
check("tokens <addr>: decimals-formatted balance (5 CAIRN, grouped)", /CAIRN\s+5\b/.test(tk.out));
check("tokens <addr>: locked amount surfaced", /1 locked/.test(tk.out));
check("tokens <addr>: 0-decimals token printed raw-exact (100)", /DEC0\s+100\b/.test(tk.out));
check("tokens <addr>: owned .csd names listed", tk.out.includes("inverse") && tk.out.includes("stone-age"));
check("tokens --json is machine-readable", JSON.parse((await run(["tokens", ME, "--json"], env)).out).balances.CAIRN.available === "500000000");
check("tokens with a bad address → friendly error", /bad address/.test((await run(["tokens", "0xnope"], env)).out));
check("tokens without any address → setup guidance (no crash)", /no address|setup/i.test((await run(["tokens"], env)).out));

const ti = await run(["token-info", "CAIRN"], env);
check("token-info: supply + minted + % of supply", /21,000,000/.test(ti.out) && /100% of supply/.test(ti.out));
check("token-info: decimals + mint mode shown", /decimals\s+8/.test(ti.out) && /issuer-only/.test(ti.out));
check("token-info: 12 holders → exactly top 10 rows", (ti.out.match(/[█░]{16}/g) || []).length === 10 && /12 · top 10/.test(ti.out));
check("token-info: open-mint token shows the per-mint limit", /open · up to 10/.test((await run(["token-info", "DEC0"], env)).out));
check("token-info: unknown ticker → 'unknown token'", /unknown token/.test((await run(["token-info", "ZZZZ"], env)).out));
check("token-info: hostile token name can't inject ANSI/OSC", !/\x1b|\x07|\x9b/.test(strip((await run(["token-info", "CAIRN"], { ...env, CAIRN_COLOR: "1", NO_COLOR: "" })).raw)));

console.log("\n— token-send: dry-run path (no csd, nothing signed) —");
const dry = await run(["token-send", "--ticker", "CAIRN", "--to", YOU, "--amount", "1.5", "--address", ME, "--dry-run"], env);
check("prints the EXACT canonical record uri", dry.out.includes(`{"amount":"150000000","t":"transfer","ticker":"CAIRN","to":"${YOU}","v":1}`));
check("prints the record's sha256 payload hash", /hash\s+0x[0-9a-f]{64}/.test(dry.out));
check("prints the 0.25 CSD anchor cost", /0\.25 CSD/.test(dry.out));
check("prints human + base units + decimals", /1\.5 CAIRN \(150000000 base units · 8 decimals\)/.test(dry.out));
check("ends in [dry-run], exit 0, csd never touched", /\[dry-run\] not signed or submitted/.test(dry.out) && dry.code === 0 && !/csd/.test(dry.out.split("record")[0]));
check("uppercases a lowercase --ticker", (await run(["token-send", "--ticker", "cairn", "--to", YOU, "--amount", "1", "--address", ME, "--dry-run"], env)).out.includes('"ticker":"CAIRN"'));
const frac0 = await run(["token-send", "--ticker", "DEC0", "--to", YOU, "--amount", "1.5", "--address", ME, "--dry-run"], env);
check("'1.5' of a 0-decimals token FAILS (never truncates)", /more decimal places/.test(frac0.out) && !/"amount":"1"/.test(frac0.out) && !/"amount":"15"/.test(frac0.out));
check("insufficient balance → blocked with both sides shown", /insufficient CAIRN: balance 5, tried to send 6/.test((await run(["token-send", "--ticker", "CAIRN", "--to", YOU, "--amount", "6", "--address", ME, "--dry-run"], env)).out));
check("locked balance does NOT count as spendable (5 avail + 1 locked, send 5.5 fails)", /insufficient/.test((await run(["token-send", "--ticker", "CAIRN", "--to", YOU, "--amount", "5.5", "--address", ME, "--dry-run"], env)).out));
check("amount 0 rejected", /amount must be > 0|bad amount/.test((await run(["token-send", "--ticker", "CAIRN", "--to", YOU, "--amount", "0", "--address", ME, "--dry-run"], env)).out));
check("bad recipient rejected before any API/csd work", /bad recipient/.test((await run(["token-send", "--ticker", "CAIRN", "--to", "0xnope", "--amount", "1", "--address", ME, "--dry-run"], env)).out));
check("unknown ticker rejected", /unknown token/.test((await run(["token-send", "--ticker", "ZZZZ", "--to", YOU, "--amount", "1", "--address", ME, "--dry-run"], env)).out));
check("missing flags → usage", /usage/.test((await run(["token-send"], env)).out));
check("real-send path without csd → guides to install (after the printed record)", /`csd` not found/.test((await run(["token-send", "--ticker", "CAIRN", "--to", YOU, "--amount", "1", "--address", ME], env)).out));

console.log("\n— names / name —");
const nm = await run(["names", ME], env);
check("names <addr> lists owned names + count", nm.out.includes("inverse") && nm.out.includes("stone-age") && /2 names/.test(nm.out));
check("names of an empty address → friendly empty state", /no names owned/.test((await run(["names", YOU], env)).out));
const n1 = await run(["name", "inverse"], env);
check("name <n>: owner + claim height", n1.out.includes(ME) && /height 30228/.test(n1.out));
check("name <n>: no lease data → explicit dash (not a fake epoch)", /lease\s+—/.test(n1.out));
check("name <n>: no open offer state", /no open offer/.test(n1.out));
const n2 = await run(["name", "leased"], env);
check("name <n>: lease paidThroughEpoch surfaced", /paid through epoch 2000/.test(n2.out));
check("name <n>: open offer → FOR SALE with the CSD price", /FOR SALE/.test(n2.out) && /0\.3 CSD/.test(n2.out));
check("name <unregistered> → friendly 404", /unregistered name/.test((await run(["name", "zzznotaname"], env)).out));
check("name <INVALID-CHARS> → usage (validated before any request)", /usage/.test((await run(["name", "Not_A_Name!"], env)).out));
check("help lists the cairnx section", /cairnx/.test((await run([], env)).out) && /token-send/.test((await run([], env)).out));

sA.close(); sB.close(); mock.close();
console.log(`\n${fail === 0 ? "ALL PASS" : "FAILURES"}: ${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
